import{a as p,S as q,i as n}from"./assets/vendor-HX_BPRhs.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&m(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function m(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();p.defaults.baseURL="https://pixabay.com/api/";async function y(s,e=1){return(await p.get("",{params:{key:"52056130-db9fbcb72f3bb5afb21255a47",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}const h=document.querySelector(".gallery"),r=document.querySelector(".loader"),g=document.querySelector(".load-more-btn");let d=null;function b(s){const e=s.map(a=>`
    <div class="card gallery-item">
      <a href="${a.largeImageURL}">
        <img src="${a.webformatURL}" alt="${a.tags}" class="gallery-images">
      </a>
      <div class="info">
        <p class="name">Likes<span class="value">${a.likes}</span></p>
        <p class="name">Views<span class="value">${a.views}</span></p>
        <p class="name">Comments<span class="value">${a.comments}</span></p>
        <p class="name">Downloads<span class="value">${a.downloads}</span></p>
      </div>
    </div>
  `).join("");h.insertAdjacentHTML("beforeend",e),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){h.innerHTML=""}function L(s=!0){r.classList.add("is-visible"),s?(r.classList.add("initial"),r.classList.remove("load-more")):(r.classList.add("load-more"),r.classList.remove("initial"))}function v(){r.classList.remove("is-visible","initial","load-more")}function w(){g.style.display="block"}function u(){g.style.display="none"}const P=document.querySelector(".search-form"),$=document.querySelector(".load-more-btn");let i="",l=1,f=0;const S=15;P.addEventListener("submit",async s=>{if(s.preventDefault(),i=s.target.elements.searchQuery.value.trim(),!i){n.warning({message:"Please enter a search term"});return}l=1,M(),u(),L(!0);try{const e=await y(i,l);if(f=e.totalHits,!e.hits.length){n.error({message:"No images found"});return}b(e.hits),Math.ceil(f/S)>1?w():(u(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong"})}finally{v()}});$.addEventListener("click",async()=>{l+=1,u(),L(!1);try{const s=await y(i,l);b(s.hits);const e=Math.ceil(f/S);l<e?w():n.info({message:"We're sorry, but you've reached the end of search results."}),B()}catch{n.error({message:"Something went wrong"})}finally{v()}});function B(){const s=document.querySelector(".gallery-item");if(s){const{height:e}=s.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
